BODY_DRIVER_REPORTERS = {"position": "position"}
KINEMATIC_BODY_DRIVER_REPORTERS = BODY_AGENT_REPORTERS | {"velocity": lambda x: x.body.velocity}
KINEMATIC_BODY_WITH_ACCELERATION_DRIVER_REPORTERS = KINEMATIC_BODY_AGENT_REPORTERS | {
    "acceleration": lambda x: x.body.acceleration
}
DYNAMIC_BODY_DRIVER_REPORTERS = KINEMATIC_BODY_WITH_ACCELERATION_AGENT_REPORTERS | {}
