version: 2
formats: []

build:
  image: latest
  apt_packages:
    - python3-dev
    - libproj-dev
    - proj-data
    - proj-bin
    - libgeos-dev
    - gdal-bin
    - libgdal-dev
python:
  version: 3
  install:
    - requirements: docs/requirements.txt
  system_packages: true
