version: 2
formats: []

build:
  os: "ubuntu-latest"
   tools:
     python: "3.9"
  image: latest
  apt_packages:
    - python3-dev
    - libproj-dev
    - proj-data
    - proj-bin
    - libgeos-dev
    - gdal-bin
    - libgdal-dev
python:
  install:
    - requirements: docs/requirements.txt
  system_packages: true
