language: python
python: 3.6
install:
  - apt install libspatialindex-dev
  - pip install -r requirements.txt
  - pip install -e .
script:
  - black . 
  - pytest --cov=dpd
after_success:
  - coveralls
