language: python
python: 3.9
install:
  - sudo apt update
  - sudo apt install python3-dev libproj-dev proj-data proj-bin libgeos-dev
  - pip install --upgrade -r requirements.txt
  - pip install -e .
script:
  - black --check . 
  - flake8
  - bandit -r .
  - pytest --cov=dpd
after_success:
  - coveralls
