language: python
python: 3.6
install:
  - sudo apt update
  - sudo apt install libspatialindex-dev
  - pip install -r requirements.txt
  - pip install -e .
script:
  - black --check . 
  - pytest --cov=dpd
after_success:
  - coveralls
