name: DPD

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: OSSF Scorecard action
      uses: ossf/scorecard-action@v2.3.1
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: "pip"
    - name: Install apt dependencies
      run: sudo apt install python3-dev libproj-dev proj-data proj-bin libgeos-dev gdal-bin libgdal-dev
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install pip dependencies
      run: pip install -r requirements.txt
    - name: Install package 
      run: pip install .
    - name: Lint with black
      run: black --check --extend-exclude "agent-based_transportation_model.ipynb" .
    - name: Lint with isort
      run: isort --check --profile black .
    - name: Lint with bandit
      run: bandit -r .
    - name: Lint with flake8
      run: flake8
    - name: Test with pytest
      run: |
        coverage run --source=dpd -m pytest tests/
    - name: Publish to coveralls.io
      run: |
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
