# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DPD

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        sudo apt install python3-dev libproj-dev proj-data proj-bin libgeos-dev gdal-bin libgdal-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
    - name: Lint with black, flake8, bandit
      run: |
        black --check .
        bandit -r .
    - name: Test with pytest
      run: |
        pytest --cov=dpd
    - name: Covert to lcov
      run: |
        coverage lcov
    - name: Publish to coveralls.io
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ github.token }}
        path-to-lcov: lcov.info
